### ISSUE TITLE
8월 1일 부터 시행하는 우편번호 5자리에대한 코드변경은 언제 하나요?

### ISSUE THREAD

**Issue by jungbaksacom** [xpressengine/xe-module-krzip#21]
8월 1일 부터 시행하는 우편번호 5자리에대한 코드변경은 언제 하나요?

나름 수정 방법 해봤어요

*우편번호 5자리로 변경 대응

tpl/template.daumapi.html
line 11, 18:
postcode => zonecode 로 치환

tpl/js/daumapi.js, tpl/js/daumapi.min.js
postcode => zonecode 로 치환

krzip.model.php
line 57:
        if(preg_match('/(?([0-9]{3}-[0-9]{3}))?/', $output[1], $matches) || preg_match('/(?([0-9]{5}))?/', $output[1], $matches))

**Comment by ghost** [comment]
기본 설정을 5자리로 변경하고, 우체국 API 문제를 수정해서 1.9.0 버전으로 업데이트 했습니다.
